# Generated by Django 4.0.6 on 2022-07-17 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_roomchat_user_roomchat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='user',
        ),
        migrations.AddField(
            model_name='roomchat',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
