# Generated by Django 4.0.6 on 2022-07-17 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_remove_roomchat_user_roomchat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
