# Generated by Django 4.0.6 on 2022-07-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_roomchat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='room_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
