# Generated by Django 4.0.6 on 2022-07-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_roomchat_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='room_url',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
